services:
  web:
    build: .
    restart: always
    ports:
      - "3400:3400"
    environment:
      DATABASE_URL: "mysql://admin:quantumSql%40123@host.docker.internal:3306/articledestiny"
      JWT_SECRET: "khusbhuArticleDestiny!#$@"
      PORT: 3400
    extra_hosts:
      - "host.docker.internal:host-gateway"
