services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "quantumSql@123"
      MYSQL_DATABASE: "articledestiny"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "quantumSql@123"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-pquantumSql@123"]
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://admin:quantumSql@123@db:3306/articledestiny"
      JWT_SECRET: "khusbhuArticleDestiny!#$@"
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
