services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://admin:quantumSql@123@host.docker.internal:3306/articledestiny"
      JWT_SECRET: "khusbhuArticleDestiny!#$@"
      PORT: 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
